version: '3.8'

services:
  redis:
    image: redis:7.0.0
    ports:
      # - "6379:6379"
      -"18638:18638"
    
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - REDIS_URL=${REDIS_URL}